// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa_JMixOpatN01z2IzlsGFkz0xWyqvjp0',
    appId: '1:167703184612:web:04941816332fd27cc318f1',
    messagingSenderId: '167703184612',
    projectId: 'shopping-time-cd9cf',
    authDomain: 'shopping-time-cd9cf.firebaseapp.com',
    storageBucket: 'shopping-time-cd9cf.appspot.com',
    measurementId: 'G-CK8MRP61D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3TFnOmnpqAqQ0dqI8dzHW0mVRJYr8tA',
    appId: '1:167703184612:android:e3a73fe7e21335e4c318f1',
    messagingSenderId: '167703184612',
    projectId: 'shopping-time-cd9cf',
    storageBucket: 'shopping-time-cd9cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVYJQcKEh2vrRFBaGAhKFfQia9ANEZo0Y',
    appId: '1:167703184612:ios:28038a9c9e56144ec318f1',
    messagingSenderId: '167703184612',
    projectId: 'shopping-time-cd9cf',
    storageBucket: 'shopping-time-cd9cf.appspot.com',
    iosClientId:
        '167703184612-euobfa9uo86jkkef5bbgi719elis9bep.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVYJQcKEh2vrRFBaGAhKFfQia9ANEZo0Y',
    appId: '1:167703184612:ios:28038a9c9e56144ec318f1',
    messagingSenderId: '167703184612',
    projectId: 'shopping-time-cd9cf',
    storageBucket: 'shopping-time-cd9cf.appspot.com',
    iosClientId:
        '167703184612-euobfa9uo86jkkef5bbgi719elis9bep.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingTime',
  );
}
